### ISSUE TITLE
Port should be configurable from command-line

### ISSUE THREAD

**Issue by AustinBGibbons** [quantifind/wisp#10]
Currently `val port = Port.any`, should expose setting a custom port.

**Comment by Mortimerp9** [comment]
It should already be:
```scala
object UnfilteredWebApp {
trait Arguments extends FieldArgs {
var headerSize: Int = (2 * 10e6).toInt // 2 megabytes
var port = Port.any
var altRoot: Option[String] = None
}
}
```
https://github.com/quantifind/wisp/blob/master/core/src/main/scala/com/quantifind/charts/repl/UnfilteredWebApp.scala#L43

or are you not using UnfilteredWebApp?

**Comment by AustinBGibbons** [comment]
It is in unfiltered, but not in the value I pass to unfiltered :-/

```
trait WebPlot[T] extends Plottable[T] {

  val serverRootFileName = s"index-${System.currentTimeMillis()}.html"
  val port = Port.any
```

I need to create better flexibility here in general, I think.
