### ISSUE TITLE
Boxplot

### ISSUE THREAD

**Issue by AustinBGibbons** [quantifind/wisp#21]
Boxplot is a work in progress here: https://github.com/quantifind/wisp/compare/austin/boxplot?expand=1

todo: 
- styling
- test-cases
- can the DataBox case class be safely assigned for this purpose?
- class name for DataBox (the case class for a box's defining parameters)
- data input format (currently list of 5-tuples or 6-tuples, or a list-of-lists)

**Comment by andypetrella** [comment]
in one word: *awesome*
