### ISSUE TITLE
Wisp on ArchLinux doesn't create file index???.html

### ISSUE THREAD

**Issue by mandubian** [quantifind/wisp#22]
Apparently `File.renameTo` didn't work on y OS (ArchLinux) and file /tmp/xxx isn't moved to /index???.html so it's not found...
Had anybody this problem?

**Comment by AustinBGibbons** [comment]
Hey, I have not yet heard of this problem.

Does your user have permissions to read/write in both /tmp/ and your current working directory?

**Comment by mandubian** [comment]
Yes apparently I have rights...
what's strange is that files are written in /tmp but not in my current
dir...

**Comment by slothspot** [comment]
Same on Fedora 20 with Oracle JDK 1.8.0_25 and Scala 2.11.5

**Comment by AustinBGibbons** [comment]
This should be fixed in 0.0.3, thanks y'all, and let me know if you have continued issues.

**Comment by AustinBGibbons** [comment]
I am seeing issues creating multiple plots, investigating
