### ISSUE TITLE
writing html fails silently

### ISSUE THREAD

**Issue by declerambaul** [quantifind/wisp#25]
Hi,

File.renameTo seems to be platform dependent and there is no check whether the renaming operation succeeded - it works on my local machine (Mac), but fails silently remotely (Linux). 

https://github.com/quantifind/wisp/blob/7345feb8dc3893273bc93d7edf34c613c12656fa/core/src/main/scala/com/quantifind/charts/repl/HighchartsImpl.scala#L52

**Comment by AustinBGibbons** [comment]
This was addressed in #29, closing
