### ISSUE TITLE
Axis Min and Max Not Persisting to JSON

### ISSUE THREAD

**Issue by looth4** [quantifind/wisp#34]
val hc = Highchart(
        series = Seq(productionSeries),
        title = Some(Title(graphTitle)),
        xAxis = Some(Array(Axis(title = Some(AxisTitle(paramName)), min = Some(0)))),
        yAxis = Some(Array(
          Axis(title = Some(AxisTitle(prodAxisTitle)), min = Some(0))
        ))
      )

Should render JSON that includes: "min":0 in both the xAxis and yAxis sections of the JSON.

This klugey workaround does the trick, but would be great for this to work in the API.
json.replaceAllLiterally("\"title\":{\"text\":\"" + prodAxisTitle + "\"}", "\"title\":{\"text\":\"" + prodAxisTitle + "\"},\"min\":0")

**Comment by AustinBGibbons** [comment]
Thanks for pointing this out Luther! PR submitted
