### ISSUE TITLE
Jackson 2.4.0 conflicts with Spark

### ISSUE THREAD

**Issue by AustinBGibbons** [quantifind/wisp#4]
Unfortunately I think spark uses an older version of jackson, and you might bump into some issues using the jackson version (2.4.0) imported by wisp

See: http://vanwilgenburg.wordpress.com/2014/10/26/fix-the-classpath-in-spark/

**Comment by AustinBGibbons** [comment]
Update: this may only affect older versions of spark. We are using jackson-2.4.0 to support scala 2.11, where as jackson-2.2.2 was the version used by spark compiled against 2.10

**Comment by asteele-quantifind** [comment]
Any Jackson version after 2.2.2 has significant problems serializing or
deserializing certain classes (not just spark).  We must be critically
careful if/when we upgrade.

**Comment by AustinBGibbons** [comment]
I am using this strategy to circumvent the problem:

```
    ("com.quantifind" %% "wisp" % "0.0.1")
      .exclude("com.fasterxml.jackson.module", "jackson-module-scala")
      .exclude("com.fasterxml.jackson.core", "jackson-annotations")
      .exclude("com.fasterxml.jackson.module", "jackson-module-jsonSchema")
      .exclude("com.fasterxml.jackson.datatype", "jackson-datatype-joda"),
```

**Comment by AustinBGibbons** [comment]
I've elected to use json4s-native over fasterxml-jackson

**Comment by andypetrella** [comment]
FYI, in the spark-notebook, I've done that https://github.com/andypetrella/spark-notebook/blob/master/project%2FDependencies.scala#L47.
So it worked fine with 2.3.3.

**Comment by stuenofotso** [comment]
set value of spark.executor.extraClassPath in SparkConf with path to updated jackson libs:

conf = SparkConf()
conf.set("spark.executor.extraClassPath", "/usr/hdp/2.4.0.0-169/spark/lib/jackson-annotations-2.4.4.jar:/usr/hdp/2.4.0.0-169/spark/lib/jackson-core-2.4.4.jar:/usr/hdp/2.4.0.0-169/spark/lib/jackson-databind-2.4.4.jar:/usr/hdp/2.4.0.0-169/spark/lib/jackson-module-scala_2.10-2.4.4.jar")
sc = SparkContext(conf=conf)
