### ISSUE TITLE
Examples in blog article fail for multiple reasons

### ISSUE THREAD

**Issue by mslinn** [quantifind/wisp#6]
[From the blog](http://www.quantifind.com/blog/2015/01/wisp-is-scala-plotting/?redirect=1). Try and see :)

````
import com.quantifind.charts.Highcharts._
import com.quantifind.charts.highcharts.Highchart._

object Test1 extends App {
  Highchart(Seq(Series(Seq(Data(1, 2)))), 
            chart = Chart(zoomType = Zoom.xy), 
		    yAxis = None
  ) 

  object Test2 extends App {
    import com.quantifind.charts.repl.Highcharts._
    areaspline(List(1, 2, 3, 4, 5), List(4, 1, 3, 2, 6))
  }
}
````

I did not go any further into the article. You folks might want to test the rest of the published code, however.

**Comment by AustinBGibbons** [comment]
Hey Mike, thanks for bringing this to my attention!

the `repl` import was outright incorrect :-/, and has been fixed 

I think the other issue you are encountering is from importing `Highcharts._` instead of `highcharts._`, which I agree is confusing. `highcharts` is the lower-level implementation and `Highchats` is the repl API. My goal is to work towards the end-user not needing to know about the lower-level implementation, but we are not there yet.

You may have also run into issues similar to #5 , in addition to `open` cross-platform support, we rely on `java.net.InetAddress.getLocalHost.getCanonicalHostName`, which I believe resolves your hostname from /etc/host

This all works for me:

```
scala> import com.quantifind.charts.highcharts.Highchart._
import com.quantifind.charts.highcharts.Highchart._

scala> import com.quantifind.charts.Highcharts._
import com.quantifind.charts.Highcharts._

scala>     areaspline(List(1, 2, 3, 4, 5), List(4, 1, 3, 2, 6))
serving resources from: file:/Users/austin/IdeaProjects/wisp/index-1421948868454.html
2015-01-22 09:47:49.232:INFO:oejs.Server:jetty-8.1.13.v20130916
2015-01-22 09:47:49.266:INFO:oejs.AbstractConnector:Started SocketConnector@0.0.0.0:62010
Server started: http://192.168.1.244:62010/index-1421948868454.html
Output written to http://192.168.1.244:62010 (CMD + Click link in Mac OSX).
res0: com.quantifind.charts.highcharts.Highchart = Highchart(List(Series(List(Data(1,4,None,None), Data(2,1,None,None), Data(3,3,None,None), Data(4,2,None,None), Data(5,6,None,None)),None,None,None,Some(areaspline),None,None,None,None,series)),Some(Title(,None,None,None,None,None,None,None,title)),Some(Chart(Some(xy))),None,Some(Credits(None,,None,None,)),Some(Exporting(chart,None,None,None,None,None,None)),None,Some(PlotOptions(None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,plotOptions)),None,true,None,None,Some([Lcom.quantifind.charts.highcharts.Axis;@4478ef79))

scala>

scala>

scala> import com.quantifind.charts.highcharts._
import com.quantifind.charts.highcharts._

scala> Highchart(Seq(Series(Seq(Data(1, 2)))), chart = Chart(zoomType = Zoom.xy), yAxis = None)
res1: com.quantifind.charts.highcharts.Highchart = Highchart(List(Series(List(Data(1,2,None,None)),None,None,None,Some(line),None,None,None,None,series)),Some(Title(,None,None,None,None,None,None,None,title)),Some(Chart(Some(xy))),None,Some(Credits(None,,None,None,)),Some(Exporting(chart,None,None,None,None,None,None)),None,Some(PlotOptions(None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,plotOptions)),None,true,None,None,None)
```

Thanks for reporting!

**Comment by mslinn** [comment]
Austin,

It compiles now, thanks. Here are the complete programs, which might be 
helpful for others:

importcom.quantifind.charts.Highcharts._
importcom.quantifind.charts.highcharts._
importcom.quantifind.charts.highcharts.Highchart._

objectTest1extendsApp {
   Highchart(Seq(Series(Seq(Data(1,2)))),
             chart = Chart(zoomType = Zoom.xy),
             yAxis = None
   )
   synchronized { wait() }
}

objectTest2extendsApp {
   areaspline(List(1,2,3,4,5),List(4,1,3,2,6))
   synchronized { wait() }
}

The docs do not mention if this is a GUI library (using Swing, etc) or a 
server-side library. I don't see any output for either app, however I 
see the following exception when running Test2:

Exception in thread "main" java.lang.NoClassDefFoundError: 
javax/servlet/Filter

Looks like this library requires a Java Servlet container. If that is 
the intention, then I suggest the dependencies be added to the POM? You 
might want to discuss this in the docs too.

I don't use servlets any more, I use and teach Play Framework, so if 
this library requires Java servlets I'll move on.

Thanks,

Mike

**Comment by AustinBGibbons** [comment]
Hey Mike, `Test1` just instantiates a Highchart object, you can call plot(obj) to plot the object.

I did not get the same error from Test2. Here is a short video showing what happens for me when I run `Test2`: https://www.dropbox.com/s/pu85qgku4vxb4lu/wisp-quick-demo.mov?dl=0

Currently this library uses [unfiltered](http://unfiltered.databinder.net/Unfiltered.html) to serve webpages, which I believe is built on top of jetty. There is secondary support for netty within unfiltered. 

Our original goal was to make it feel very interactive, so we chose to tightly couple the server with the plotting functionality, but I think the best course of action would be to decouple the server from core/, perhaps creating `wisp-jetty`, `wisp-netty`, or `wisp-play` to allow greater flexibility / capability around integrating with other libraries.
