### ISSUE TITLE
Support open on more platforms

### ISSUE THREAD

**Issue by AustinBGibbons** [quantifind/wisp#7]
`open` only works on some unix distributions, `xdg-open` from #5 should help, but I have not tested behavior on Windows, but would like to support the same functionality.

**Comment by Mortimerp9** [comment]
should have commented here, sorry:


You should be able to do something like this to be cross platform and not have a special case for each platform:

```scala
import java.awt.Desktop
import java.net.URI
if(Desktop.isDesktopSupported()){
  Desktop.getDesktop().browse(new URI("http://www.example.com"))
}
```

from http://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java

**Comment by AustinBGibbons** [comment]
Nice! Thanks Pierre, it's been folded into #5
